#!/bin/bash

# bash aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

# Even easier navigation with some common destinations
alias p="cd ~/projects"

# Trim newlines then copy to clipboard
alias c="tr -d '\n' | pbcopy"

# IP addresses
# My public ip
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# LS Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Grep aliases
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# An "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"