#!/usr/bin/env bash

# bash aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

# Even easier navigation with some common destinations
alias p="cd ~/projects"
alias t="cd /tmp"

# Trim newlines then copy to clipboard
alias c="tr -d '\n' | pbcopy"

# Remove leading and trailing quotations
alias unquote="sed -e 's/^\"//' -e 's/\"$//'"

# IP addresses
# My public ip
alias ip4="dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com | unquote"
alias ip6="dig -6 TXT +short o-o.myaddr.l.google.com @ns1.google.com | unquote"

# LS Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Grep aliases
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# An "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# Use python3
alias python="python3"

# Case change aliases
alias toupper="tr [:lower:] [:upper:]"
alias tolower="tr [:upper:] [:lower:]"

# Commonly used program aliases
alias g="git"
alias k="kubectl"
