#!/usr/bin/env bash

# bash profile

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Up-front dotfiles configuration
# Not part of `load_dotfiles` because it must be sourced before anything else
# to be sure that commands like `brew` (when installed in a custom location)
# are already added to the PATH.
[ -r $HOME/.dotfilesrc ] && source $HOME/.dotfilesrc;

load_dotfiles() {
    declare -a files=(
        $HOME/.rvm/scripts/rvm                  # Load RVM into a shell session *as a function*
        $HOME/.dotfiles/bash/options            # Options
        $HOME/.dotfiles/bash/exports            # Exports
        $HOME/.dotfiles/bash/aliases            # Aliases
        $HOME/.dotfiles/bash/extras             # Extras
        $HOME/.dotfiles/bash/functions/*        # Functions
        $HOME/.dotfiles/bash/prompt             # Custom bash prompt
        $HOME/.dotfiles/bash/paths              # Path modifications
        $HOME/.dotfiles/bash/wsl                # WSL specific scripts
        # $(brew --prefix)/etc/bash_completion    # Bash completion (installed via Homebrew)
        $HOME/.bash_profile.local               # Local and private settings not under version control (e.g. git credentials)
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

load_dotfiles
unset load_dotfiles
. "$HOME/.cargo/env"
